### ISSUE TITLE
No indicator in Xenial

### ISSUE THREAD

**Issue by 3arn0wl** [bhdouglass/ut-indicator-weather#11]
It's probably just me being my usual inept self, but I don't seem to be able to get the icon in Notifications since I upgraded to 16.04 dev on Hammerhead.

I find ut-indicator-weather to be a really useful app, and I am missing it.

**Comment by bhdouglass** [comment]
Have you tried uninstalling/installing from the app then restarting your phone?

**Comment by 3arn0wl** [comment]
I uninstalled with UT Tweak this time; clearing the cache etc. before I deleted the app.  I reinstalled, and pasted in a new API key, put my long/lat in, and saved. I've rebooted twice, but there's still no icon, sadly.

Hammerhead: 16.04: latest dev image

**Comment by 3arn0wl** [comment]
:) Hi

It seems to be working now. Several reboots did the trick. I also had to change to DarkSky, as it didn't seem to like OpenWeatherMap any more...

Anyway - thanks so much for producing such a good little app, and for coming to my rescue.

**Comment by bhdouglass** [comment]
weird, maybe open weather map was causing it to crash or something. I'm glad it's working for you now!
