### ISSUE TITLE
OpenWeatherMap provider not working on Xenial

### ISSUE THREAD

**Issue by arubislander** [bhdouglass/ut-indicator-weather#12]
Hi,

Great job with this program. I depend on this so much, I glance at the indicator before looking out the window, LOL.

I am not sure if this is a xenial only problem, but the owm provider does not work. Darksky works great. I have also tried different owm api keys. I see that @3arnowl had a similar issue.

Thanks again fir your work!

**Comment by bhdouglass** [comment]
I'm glad you like it! I'll take a look and see what happened with OWM.

**Comment by bhdouglass** [comment]
This has been fixed in v1.3.0!
