### ISSUE TITLE
Add support for other weather forecast services [wishlist]

### ISSUE THREAD

**Issue by ghost** [bhdouglass/ut-indicator-weather#2]
Very nice work on this indicator!
Would it be possible to add support for other weather forecast services (especially [Open Weather Map](http://openweathermap.org/api))?
Here is the source code for [a similar project on Unity 7](https://git.launchpad.net/my-weather-indicator/tree/) if it can help.

**Comment by bhdouglass** [comment]
I'm familiar with OpenWeatherMap and other providers as I have written a nodejs library for various APIs. I started with only one so I could release a minimally "complete" indicator. But I'm not opposed to adding more options, so I'll add this to my to do list.

**Comment by bhdouglass** [comment]
I just added support for Open Weather Map in v1.20, let me know if you have any issues with it!

**Comment by ghost** [comment]
You are just AWSOME, thank you so much for your hard work!
I can't test this new version yet since I have no Ubuntu phone / tablet, but I have translated the new strings created in v1.20 in Launchpad.

**Comment by bhdouglass** [comment]
You are very welcome! Thanks for the translations, expect a new release with the updated strings soon.
