### ISSUE TITLE
Doesnt update if no internet at boot

### ISSUE THREAD

**Issue by cm-t** [bhdouglass/ut-indicator-weather#3]
* switch off wifi, or let it on, in an area you don't have a paired yet wifi
* you can swith on Cell data
* reboot
* give your SIM PIN
* now on lock screen: No weather data in indicator
  * data from cell was not yet up when indicator tryed to fetch weather, it was probably trying before the SIM PIN prompt
  * and according to first step, data from wifi was not yet swithed on or connected too.
* now enable internet (wifi or cell)
* wait
* nothing will happend
* ever :'(
* only rebooting with WIFI will get the first weather fetch and then havind it up to date

Not having internet on boot should not stop trying to update the weather like it does currently.

**Comment by bhdouglass** [comment]
Thanks for the feedback! I'm in the process of adding better error handling and will let you know when I upload a new version.

**Comment by bhdouglass** [comment]
I just uploaded v1.13 to the OpenStore, it contains better error handling and also will retry to get the weather data in the event of an error. This should fix the issues you ran into.

**Comment by nuisgenug** [comment]
Still no uptate after disabling wifi - after rebooting it works again 1.22

**Comment by bhdouglass** [comment]
Make sure you reboot after every app update, that way the indicator can update as well. If you continue to run into issues just let me know!

**Comment by nuisgenug** [comment]
It doesn't happen after an update of the settings - it always happens after being in flight mode over night...

**Comment by bhdouglass** [comment]
Unfortunately it won't update right away when you turn on your WiFi, you'll have to wait up to 15 minutes. I want to look into programmatically detecting a network connection so that wait time isn't there.
