### ISSUE TITLE
[Whislist] Add support for coordinates directly taken by GPS

### ISSUE THREAD

**Issue by TronFortyTwo** [bhdouglass/ut-indicator-weather#4]
This could be helpful while travelling, or simply if you work/study and live in two different cities. Thank you for all the work you're doing!

**Comment by bhdouglass** [comment]
Yeah, this is on my TODO list, I need to figure out where I can grab the coordinates from since the indicator is outside the normal app stuff.

**Comment by Telstan** [comment]
How can I get the API code?

**Comment by bhdouglass** [comment]
@Telstan which api are you talking about?

**Comment by Telstan** [comment]
The one for the Weather Indicator app.

**Comment by bhdouglass** [comment]
I'm not sure how this relates to this ticket about GPS support. But you can find an api key from [OpenWeatherMap](https://openweathermap.org/appid) or [Dark Sky](https://darksky.net/poweredby/).

**Comment by Telstan** [comment]
Sorry to have used the wrong forum. My apologies

**Comment by bhdouglass** [comment]
No worries, just go ahead and open a new ticket next time.

**Comment by bhdouglass** [comment]
Moved to gitlab: https://gitlab.com/bhdouglass/indicator-weather/issues/4
