### ISSUE TITLE
[Whislist] Add support of weather fext

### ISSUE THREAD

**Issue by TronFortyTwo** [bhdouglass/ut-indicator-weather#5]
As far as I know this feature is supported by OpenWeatherMap, so could be helpful for lazy guys. Thanks for have implemented also OpenWeatherMap!

**Comment by bhdouglass** [comment]
This wouldn't be to hard to add, I'll add it to my TODO list.

**Comment by bhdouglass** [comment]
Moved to gitlab: https://gitlab.com/bhdouglass/indicator-weather/issues/5
