### ISSUE TITLE
[wishlist] Forcast in notification area

### ISSUE THREAD

**Issue by nuisgenug** [bhdouglass/ut-indicator-weather#6]
It would be great to have a 5-days forcast when pulling down the notification areea

**Comment by bhdouglass** [comment]
I agree, this is high on my to do list.

**Comment by nuisgenug** [comment]
Cool, many thanks for your work

**Comment by kolopeda** [comment]
Good apps, thank you

**Comment by bhdouglass** [comment]
Moved to gitlab: https://gitlab.com/bhdouglass/indicator-weather/issues/6
