### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by nuisgenug** [bhdouglass/ut-indicator-weather#7]
When in error level (failed to update - ! In cloud icon) the links to forecast and settings in pulldown are not working - BQ 4.5

**Comment by bhdouglass** [comment]
I wasn't able to reproduce this, but I have a feeling that v1.24 that I just uploaded might fix your issue. Can you check it out and see if that solves it?

**Comment by bhdouglass** [comment]
If you are still having problems let me know, feel free to reopen this ticket.
