### ISSUE TITLE
AGPS localisation

### ISSUE THREAD

**Issue by ernesst** [bhdouglass/ut-indicator-weather#9]
Hi, 

Two requests, since i consider your app as a must have:

- UBport brought AGPS localization to all phones, would it be possible to use it for the app ? 

- If Agps localization is activated, it would be interesting to ship it within in the UBport image. It would a nice feature. What do you think about it ? People will stay free to activate the app with a API key or not. 

thanks for the work.

**Comment by bhdouglass** [comment]
Using the AGPS/GPS system would be great, I just need to figure out how to do that (see issue #4).

I would be open to shipping it with the ubports image, if the ubports people are interested.

I'm going to close this issue since it's mostly a duplicate of #4.
